#!/bin/bash

#comment

#takes first argument
#echo $1 >> ~/notes.txt

#takes all argumentsnts
#echo $* >> ~/notes.txt

#get the topic - first argument
topic="$1"

#file to write to
filename=~/${topic}notes.txt

#request input
read -p "what do you want then? " note

#check input
if [[ $note ]]; then
    #adds date to note
    #double quotes on $filename allows spaces in filename
    echo $(date): $note >> "$filename"
    echo Note \'$note\' saved to $filename
else
    echo "No Input - no save"
fi
